# Выходной файл с анаграммами
OUTPUT_FILE=output.txt

# Лог-файл
LOG_FILE=app.log

# Минимальный уровень логирования
LOG_LEVEL=INFO

# Вывод лога в консоль
CONSOLE_LOG=true

# Максимальное количество анаграмм для вывода в консоль
MAX_DISPLAY=100